Gawader/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Gawader.Areas.Identity.Data;

namespace Gawader.Controllers
{
    public class RolesController : Controller
    {

        private readonly RoleManager<IdentityRole> _roleManager;
        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        [Authorize(Roles = "Admin, SuperAdmin")]
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, SuperAdmin")]
        public async Task<IActionResult> AddRole(string roleName)
        {
            if (roleName != null)
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
            }
            return RedirectToAction("Index");
        }
    }
}

Gawader/Controllers/ShipsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Gawader.Data;
using Gawader.Models;
using System.Security.Claims;
namespace Gawader.Controllers
{
    public class ShipsController : Controller
    {

        private readonly GawaderContext _dbContext;
        public ShipsController(GawaderContext dbContext)
        {
            this._dbContext = dbContext;
        }

        public async Task<IActionResult> Index()
        {
            var ships = await _dbContext.ShipModels.ToListAsync();

            var vwShips = new List<ShipsViewModel>();

            foreach (Ships sh in ships)
            {
                var thisShipModel = new ShipsViewModel();
                thisShipModel.ShipIndex = sh.ShipIndex;
                thisShipModel.ShipName = sh.ShipName;
                thisShipModel.ShipDescription = sh.ShipDescription;
                thisShipModel.AnchorNumber = sh.AnchorNumber;
                thisShipModel.CategoryId = sh.CategoryId;
                thisShipModel.CountryIndex = sh.CountryIndex;
                thisShipModel.NumberOfItems = sh.NumberOfItems;

                vwShips.Add(thisShipModel);
            }

            return View(vwShips);

        }

        [HttpGet]
        public IActionResult PostShips()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PostShips(ShipsViewModel vwship)
        {
            if (ModelState.IsValid)
            {
                Ships ships = new Ships();

                ships.ShipName = vwship.ShipName;
                ships.ShipDescription = vwship.ShipDescription;

                ships.ShipCapacity = vwship.ShipCapacity;
                ships.AnchorNumber = vwship.AnchorNumber;
                ships.CountryIndex = vwship.CountryIndex;

                ships.CategoryId = vwship.CategoryId;
                ships.NumberOfItems = vwship.NumberOfItems;
                ships.DateOfArrival = vwship.DateOfArrival;
                ships.EnterAt = DateTime.Now;

                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                ships.EnterBy = userId;


                await _dbContext.ShipModels.AddAsync(ships);
                await _dbContext.SaveChangesAsync();

            }

            return RedirectToAction("Index");
        }
    }
}

Gawader/Controllers/UserRolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Gawader.Areas.Identity.Data;
using Gawader.Models;

namespace Gawader.Controllers
{
    public class UserRolesController : Controller
    {

        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public UserRolesController(UserManager<AppUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index2()
        {
            return View();
        }

        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.ToListAsync();
            var UserRoles = new List<UserRolesViewModel>();
            //var roles = await _roleManager.Roles.ToListAsync();

            foreach (AppUser user in users)
            {
                var thisUserModel = new UserRolesViewModel();
                thisUserModel.UserId = user.Id;
                thisUserModel.UserName = user.UserName;
                thisUserModel.Email = user.Email;
                thisUserModel.FirstName = user.FirstName;
                thisUserModel.LastName = user.LastName;
                thisUserModel.Roles = await GetUserRoles(user);

                UserRoles.Add(thisUserModel);

            }
            return View(UserRoles);

        }

        private async Task<List<string>> GetUserRoles(AppUser user)
        {

            return new List<string>(await _userManager.GetRolesAsync(user));
        }


        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Manage(string UserId)
        {
            ViewBag.userId = UserId;

            var user = await _userManager.FindByIdAsync(UserId);

            if (UserId == null || user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {UserId} cannot be found";
                return View("NotFound");
            }

            ViewBag.UserName = user.UserName;

            var model = new List<ManageUserRolesViewModel>();

            foreach (var role in _roleManager.Roles)
            {
                var userRolesviewModel = new ManageUserRolesViewModel()
                {
                    RoleId = role.Id,
                    RoleName = role.Name,
                };

                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesviewModel.Selected = true;
                }
                else
                {
                    userRolesviewModel.Selected = false;
                }
                model.Add(userRolesviewModel);

            }
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Manage(List<ManageUserRolesViewModel> model, string UserId)
        {
            var user = await _userManager.FindByIdAsync(UserId);

            if (UserId == null || user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {UserId} cannot be found";
                return View();
            }
            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Can not remove user existing role.");
                return View(model);

            }


            result = await _userManager.AddToRolesAsync(user, model.Where(x => x.Selected).Select(y => y.RoleName));
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Can not add selected role to the user.");
                return View(model);

            }

            return RedirectToAction("Index");

        }
    }
}

Gawader/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Gawader.Areas.Identity.Data

<!DOCTYPE html>
<html lang="en">
@inject SignInManager<AppUser> signInManager;
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Gawader</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Gawader.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gawader</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>

						@if (signInManager.IsSignedIn(User) && (User.IsInRole("Admin") || User.IsInRole("SuperAdmin")))
						{
							<li class="nav-item">
							<a class="nav-link text-dark" asp-area="Identity" asp-controller="Roles" asp-action="Index">Roles</a>
						</li>

						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="Identity" asp-controller="UserRoles" asp-action="Index">Users</a>
						</li>

							
						}
						
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Ships" asp-action="Index">Ships</a>
						</li>
					</ul>
				</div>
				<partial name="_LoginPartial" />
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2022 - Gawader - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>